export { compareArray } from "./compareArray";
export { compareTuples } from "./compareTuples";
export { createInvokable } from "./createInvokable";
export { default as deepCompareQuery } from "./deepComparisons";
export { default as isUUID } from "./isUUID";
export { insertCacheOptions } from "./insertCacheOptions";
export { insertODataQuery } from "./insertODataQuery";
export { resolveList } from "./resolveList";
export { resolveWeb } from "./resolveWeb";
export { shallowEqual } from "./shallowEqual";