export { compareArray } from "./compareArray";
export { compareTuples } from "./compareTuples";
export { createInvokable } from "./createInvokable";
export { deepCompareQuery } from "./deepComparisons";
export { insertCacheOptions } from "./insertCacheOptions";
export { insertODataQuery } from "./insertODataQuery";
export { isEmail } from "./isEmail";
export { isUUID } from "./isUUID";
export { isUrl, UrlType } from "./isUrl";
export { resolveList } from "./resolveList";
export { resolveWeb } from "./resolveWeb";
export { shallowEqual } from "./shallowEqual";